### ISSUE TITLE
Can't open Shiftnet in Memphis

### ISSUE THREAD

**Issue by dragonexagon** [shiftosnext/shiftos-next#8] opened 2015-07-11 12:19 UTC
![nigger](https://cloud.githubusercontent.com/assets/9765171/8633713/aa0a0c36-27d7-11e5-8cc1-a97d486466ce.png)

**Comment by TheUltimateHacker** [comment] 2015-07-11 21:45
What version of ShiftOS-Next were you running? Did you fully install the MDE (i.e waiting till 12:00 PM for Jonathan Ladouceur to contact you or running "debugmode" and then "test mdestory" in the Terminal)? Have you tried running "debugmode" and running the .saa file? That can give you a backend Visual Basic exception through the Terminal, which can help me debug the issue for you.

Thanks!

**Comment by dragonexagon** [comment] 2015-07-13 13:08
0.0.2 Alpha 2 ... it's an alpha. you nigger

**Comment by dragonexagon** [comment] 2015-07-13 13:15
I fiixded it. but seriusly 12pm?

**Comment by RandomMelon** [comment] 2015-07-26 16:29
As said above, the issue is now fixed, closed.

**Closed by RandomMelon** 2015-07-26 16:29 UTC
